"""add technodom smartphone

Revision ID: 65ad8d2de9f0
Revises: 600b6bf12e23
Create Date: 2023-01-28 23:31:52.154191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ad8d2de9f0'
down_revision = '600b6bf12e23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technodom_smartphone',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('memory', sa.String(length=20), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technodom_smartphone_price'), 'technodom_smartphone', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technodom_smartphone_price'), table_name='technodom_smartphone')
    op.drop_table('technodom_smartphone')
    # ### end Alembic commands ###
